libhinawa.spec

buildrequireの不足分の追加。
通常パッケージとdevelopmentパッケージの分離。
Notice:
rpmbuildを実行するには、事前にlibhinawa-0.5.0.tar.gzをローカルに準備する必要がある。

fix some issue.

---

debian/control

At least, Ubuntu precise or later, Debian GNU/Linux wheezy or later
are supported even though debhelper 9 is required.

debian: follow the declared debian compatibility in debian/compat

---

debian/copyright

This commit fixes following the warning:
W: libhinawa source: missing-license-paragraph-in-dep5-copyright lgplv2 (paragraph at line 5)
License: field should be fixed too. (another PR)

debian: add missing license description

---

debian/changelog

Without this change, dpkg-source claims an error.
dpkg-source: error: can't build with source format '3.0 (quilt)': non-native package version does not contain a revision

debian: add missing debian revision

---

src/Makefile.am

This commit fixes following the error:
fw_unit.c:9:22: fatal error: internal.h: No such file or directory
compilation terminated.

Add missing internal.h

---

debian/rules

This PR make debian/rules simple.
* Remove redundant override rules
* Do not generate -dbg package by hand

debian: use simple rules

---

debian/rules

dh_auto_configure works well without it.
dh_auto_configure -- --enable-gtk-doc --enable-static=no
./configure --build=x86_64-linux-gnu --prefix=/usr --includedir=\${prefix}/include --mandir=\${prefix}/share/man --infodir=\${prefix}/share/info --sysconfdir=/etc --localstatedir=/var --disable-silent-rules --libdir=\${prefix}/lib/x86_64-linux-gnu --libexecdir=\${prefix}/lib/x86_64-linux-gnu --disable-maintainer-mode --disable-dependency-tracking --enable-gtk-doc --enable-static=no

debian: remote redundant --prefix option

---

debian/control

See https://wiki.debian.org/AutomaticDebugPackages about detail
of current dbgsym and dbg package situation.

debian: add more description about -dbgsym and -dbg package

---

src/Makefile.am

Marshal functions aren't needed for users.

Autotools: stop to install needless a header file

---

src/Makefile.am

Marshal functions should be generated before building normal sources.

Autotools: fix build time dependency

---

debian/control

debian policy is now revised to 3.9.8:
ref. https://www.debian.org/doc/debian-policy/upgrading-checklist.html

debian: bump standars-version to 3.9.8

---

debian/changelog
debian/control

When Uploaders: field is specified, "* Team upload" entry is not needed
because it is used for the case who is not listed in Maintainer: nor
Uploaders: filed.

debian: add Uploaders: field

---

debian/changelog

Remove non package related entry (It should be described in NEWS) and
bumped version to 0.8.1-1 for experimental.
(0.8.0-1 entry is removed because I didn't submit RFS actually)

debian: refresh entry for experimental

---

debian/changelog

P: experimental-to-unstable-without-comment

debian: add missing comment to fix pedantic notification

---

configure.ac

We don't use NEWS, INSTALL and so on. Automake doesn't require these
files by "foreign" option.
See also: http://www.gnu.org/software/automake/manual/automake.html#index-foreign-strictness

Autotools: stop to include unused files

---

samples/gtk3.py
samples/qt5.py
src/fw_fcp.c
src/fw_fcp.h
src/fw_node.c
src/fw_node.h
src/fw_req.c
src/fw_req.h
src/fw_resp.c
src/hinawa.map
src/hinawa_enum_types.h
src/internal.h
src/snd_dg00x.c
src/snd_dice.c
src/snd_dice.h
src/snd_efw.c
src/snd_efw.h
src/snd_motu.c
src/snd_tscm.c
src/snd_unit.c
src/snd_unit.h
tests/hinawa-enum

This merge request is a replacement of #61 with further enhancement.
In [guideline of GLib's GError](https://developer.gnome.org/gconf/stable/gconf-gconf-error.html), the naming scheme of GQuark for error domain is <namespace>_<module>_error_quark. Additionally, GLib enumeration should be implemented for error code and the naming scheme is <NAMESPACE>_<MODULE>_ERROR_<CODE>. GError should be instanciated just for recoverable runtime error.
Although GError is used in libhinawa for error reporting, the usage is not compliant to the above guideline. This commit enhances for it.
Fortunately, accessor methods to each instance of GQuark are not public, therefore it's possible to improve without any regressions.

enhancement for error reporting

---

src/fw_fcp.c
src/fw_node.c
src/fw_req.c
src/fw_resp.c
src/hinawa_enum_types.h
src/snd_dice.c
src/snd_efw.c
src/snd_tscm.c
src/snd_unit.c
tests/hinawa-enum

In [guideline of GLib's GError](https://developer.gnome.org/gconf/stable/gconf-gconf-error.html), it's better to add `failed` entry into enumerations for error to report unrecoverable error. In libhinawa, errors from system call is the kind.
This commit adds the `failed` errors into fw_node/snd_unit, with some fixes.

fw_node/snd_unit: add failed errors

---

src/fw_fcp.c
src/fw_fcp.h
src/fw_node.c
src/fw_req.c
src/fw_req.h
src/fw_resp.c
src/fw_resp.h
src/hinawa_enum_types.h
src/snd_dg00x.c
src/snd_dg00x.h
src/snd_dice.c
src/snd_dice.h
src/snd_efw.c
src/snd_efw.h
src/snd_motu.c
src/snd_motu.h
src/snd_tscm.c
src/snd_tscm.h
src/snd_unit.c
src/snd_unit.h

During 7 years for development, there are missing annotations in some APIs. This patchset is to correct them.
```
Takashi Sakamoto (11):
fw_node: add missing annotations and correct
fw_req: add missing annotations and correct
fw_resp: add missing annotations and correct
fw_fcp: add missing annotations and correct
snd_unit: add missing annotations and correct
snd_dice: add missing annotations and correct
snd_dg00x: add missing annotations and correct
snd_motu: add missing annotations and correct
snd_tscm: add missing annotations and correct
snd_efw: add missing annotations and correct
enum: add missing annotations and correct
src/fw_fcp.c            | 18 ++++++++++++
src/fw_fcp.h            |  2 ++
src/fw_node.c           | 65 ++++++++++++++++++++++++++++++++---------
src/fw_req.c …
```

[PATCH 00/11] add missing annotations and correct existent annotations

---

src/fw_node.c
src/fw_resp.c
src/fw_resp.h
src/hinawa.map
tests/fw-resp

Linux FireWire subsystem allows applications to reserve range of address within specified region of address in OHCI 1394 host controller. This commit adds new API for it.
```
Takashi Sakamoto (2):
fw_resp: add properties for offset and width to express reserved range of address
fw_resp: add API to look up region of address and reserve range of address.
src/fw_node.c  |  3 +-
src/fw_resp.c  | 81 +++++++++++++++++++++++++++++++++++++++++++-------
src/fw_resp.h  |  3 ++
src/hinawa.map |  5 ++++
tests/fw-resp  |  3 ++
5 files changed, 84 insertions(+), 11 deletions(-)
```

[PATCH 0/2] fw_resp: add API to look up region of address and reserve range of address.

---

README.rst
src/fw_fcp.c
src/fw_fcp.h
src/fw_node.c
src/fw_node.h
src/fw_req.c
src/fw_req.h
src/fw_resp.c
src/fw_resp.h
src/meson.build
src/snd_dg00x.h
src/snd_dice.c
src/snd_dice.h
src/snd_efw.c
src/snd_efw.h
src/snd_motu.c
src/snd_motu.h
src/snd_tscm.c
src/snd_tscm.h
src/snd_unit.c
src/snd_unit.h

GObject v2.44 got new macro to declare GObject-derived objects. This enables us to reduce
boireplate for the declaration.
This patchset is to replace current boireplates with it.
```
Takashi Sakamoto (10):
fw_node: use an utility macro to declare GObject-derived object
fw_req: use an utility macro to declare GObject-derived object
fw_resp: use an utility macro to declare GObject-derived object
fw_fcp: use an utility macro to declare GObject-derived object
snd_unit: use an utility macro to declare GObject-derived object
snd_dg00x:: use an utility macro to declare GObject-derived object
snd_dice: use an utility macro to declare GObject-derived object
snd_efw: use an utility macro to declare GObject-derived object
snd_motu: use an utility macro to declare GObject-derived object
snd_tscm: use …
```

[PATCH 00/10] use utility macro to declare GObject-derived objects

---

README.rst
src/fw_fcp.c
src/fw_fcp.h
src/fw_node.c
src/fw_node.h
src/fw_req.c
src/fw_req.h
src/fw_resp.c
src/fw_resp.h
src/meson.build
src/snd_dg00x.h
src/snd_dice.c
src/snd_dice.h
src/snd_efw.c
src/snd_efw.h
src/snd_motu.c
src/snd_motu.h
src/snd_tscm.c
src/snd_tscm.h
src/snd_unit.c
src/snd_unit.h

GObject v2.44 got new macro to declare GObject-derived objects. This
enables us to reduce boireplate for the declaration.
This patchset is to replace current boireplates with it.
```
Takashi Sakamoto (11):
fw_node: use an utility macro to declare GObject-derived object
fw_req: use an utility macro to declare GObject-derived object
fw_resp: use an utility macro to declare GObject-derived object
fw_fcp: use an utility macro to declare GObject-derived object
snd_unit: use an utility macro to declare GObject-derived object
snd_dg00x:: use an utility macro to declare GObject-derived object
snd_dice: use an utility macro to declare GObject-derived object
snd_efw: use an utility macro to declare GObject-derived object
snd_motu: use an utility macro to declare GObject-derived object
snd_tscm: use …
```

[PATCH 00/11] use utility macro to declare GObject-derived objects

---

tests/fw-fcp
tests/fw-node
tests/fw-req
tests/fw-resp
tests/helper.py
tests/hinawa-enum
tests/hinawa-functions
tests/meson.build
tests/snd-dg00x
tests/snd-dice
tests/snd-efw
tests/snd-motu
tests/snd-motu-register-dsp-parameter
tests/snd-tscm
tests/snd-unit

Current implementation of test just supports GObject-derived object,
enumerations, and flags. It's not possible to test the other types of
glib/gobject elements such as boxed structure.
This patchset refines test implementation. Some helper functions for
boxed structure and namespace/object functions are added. The existent
helper function is renamed as 'test_object' and rewritten to walk through
Python MRO hierarchy to check properties, virtual methods, and signals,
defined by both GObject-derived objects and interfaces.
I note that the tests are not done to execute actual symbols. They are just
to check they are available or not via interface described in metadata of
GObject Introspection.
```
Takashi Sakamoto (6):
tests: rename helper function to test object interface
tests: add helper …
```

[PATCH 0/6] tests: refine test implementation

---

src/fw_fcp.h
src/fw_node.c
src/fw_node.h
src/fw_req.c
src/fw_req.h
src/fw_resp.c
src/fw_resp.h
src/internal.h
src/snd_dg00x.h
src/snd_dice.h
src/snd_efw.h
src/snd_motu.h
src/snd_tscm.h
src/snd_unit.h

When application runs in Linux kernel with old ABI of FireWire subsystem,
some event is not available. For the case, current implementation does
not emit GObject signal corresponding to it. It's inconvenient.
This commit emits the GObject signal in the case as well as refactors code.
```
Takashi Sakamoto (4):
fw_node: code refactoring to use union type to distinguish events
fw_node: code refactoring to use const qualifier to buffer of event
fw_resp: get previous version of event back for request event
all: remove trailing semicolon when using G_DECLARE_DERIVABLE_TYPE
src/fw_fcp.h    |  2 +-
src/fw_node.c   | 33 +++++++++++++++++++++---------
src/fw_node.h   |  2 +-
src/fw_req.c    |  3 +--
src/fw_req.h    |  2 +-
src/fw_resp.c   | 54 ++++++++++++++++++++++++++++++++++++++++++++----- …
```

[PATCH 0/4] fw_resp: emit events under old ABI kernel

---

samples/common/__init__.py
src/cycle_time.c
src/cycle_time.h
src/fw_fcp.c
src/fw_fcp.h
src/fw_req.c
src/fw_req.h

PyGObject nowadays can handle argument with 'out caller-allocate' annotation expectedly for fixed-size of array, thus no need to use double pointer for out parameter.
This series is to simplify fixed-size of array processing.
```
Takashi Sakamoto (5):
cycle_time: constify self parameter when retrieving parameter
cycle_time: use suitable name for argument of fields
cycle_time: use caller-allocate strategy for fixed-size of array
fw_req: use caller-allocate strategy for fixed-size of array
fw_fcp: use caller-allocate strategy for fixed-size of array
samples/common/__init__.py | 28 +++++++---------
src/cycle_time.c           | 44 +++++++++++++------------
src/cycle_time.h           | 13 ++++----
src/fw_fcp.c               | 67 +++++++++++++++-----------------------
src/fw_fcp.h …
```

[PATCH 0/5] use caller-allocate strategy for fixed-size of array

---

README.rst
samples/common/__init__.py
src/fw_fcp.c
src/fw_req.c
src/fw_req.h
src/hinawa.map
tests/fw-req

As issued in #89 , in the convention of GNOME project, the keywords, `sync` and `async`, are used to distinguish asynchronous I/O. I misunderstood and misuse them for blocking/non-blocking API in `Hinawa.FwReq`.
This commit adds an alternative function to deprecate the previous methods. `Hinawa.FwReq.request()` is newly added to obsolete `Hinawa.FwReq.transaction_async()`. `Hinawa.FwReq.transaction_with_tstamp_sync()` is renamed to `Hinawa.FwReq.transaction_with_tstamp()` and obsoletes `Hinawa.FwReq.transaction_sync()`.
As a result, user space application is encouraged to use `Hinawa.FwReq.transaction_with_tstamp()`, `Hinawa.FwReq.request()`.
```
Takashi Sakamoto (2):
fw_req: remove 'sync' suffix from
Hinawa.FwReq.transaction_with_tstamp()
fw_req: add Hinawa.FwReq.request() to obsolete …
```

fw_req: obsolete usage of `sync` and `async` suffixes for method

---

samples/common/__init__.py
samples/gtk3
samples/gtk4
samples/qt5
src/cycle_time.h
src/fw_fcp.c
src/fw_fcp.h
src/fw_node.c
src/fw_node.h
src/fw_req.c
src/fw_req.h
src/fw_resp.c
src/fw_resp.h
src/hinawa.h
src/hinawa.map
src/hinawa_enum_types.h
src/internal.h

In GLib convention, the function with GLib.Error should return gboolean to report error.
* https://docs.gtk.org/glib/error-reporting.html
Some functions still returns void even if they have an argument for GLib.Error.
This series fixes the issue, filed at #91 .
```
Takashi Sakamoto (10):
rename include guards with ORG_KERNEL prefix instead of ALSA prefix
fw_node: change signature of FwNode.open()
fw_node: change signature of FwNode.get_config_rom()
fw_node: change signature of FwNode.create_source()
fw_req: change signature of FwReq.transaction()
fw_resp: change signature of FwResp.reserve_within_region()
fw_resp: change signature of FwResp.reserve()
fw_fcp: change signature of FwFcp.bind()
fw_fcp: change signature of FwFcp.command()
fw_fcp: change signature of FwFcp.avc_transaction() …
```

[PATCH 0/10] change signatures of functions with GLib.Error

---

samples/common/__init__.py
src/fw_fcp.c
src/fw_fcp.h
src/fw_node.c
src/fw_node.h
src/fw_req.c
src/fw_req.h
src/fw_resp.c
src/fw_resp.h
src/hinawa.map
tests/fw-fcp
tests/fw-req
tests/fw-resp

Now each object class has a sole signal, while the name of signal still includes the numeric suffix.
The series removes the suffix. Additionally, removes useless `*const` from prototypes of some functions.
```
Takashi Sakamoto (6):
fw_req: remove numeric suffix from signal
fw_resp: remove numeric suffix from signal
fw_fcp: remove numeric suffix from signal
fw_req: change prototype of FwReq.request()
fw_node: change prototype of FwNode.read_cycle_time()
remove unused global symbol
samples/common/__init__.py | 18 +++++++-------
src/fw_fcp.c               | 48 +++++++++++++++++++-------------------
src/fw_fcp.h               |  8 +++----
src/fw_node.c              |  4 ++--
src/fw_node.h              |  2 +-
src/fw_req.c               | 30 ++++++++++++------------
src/fw_req.h …
```

[PATCH 0/6] rename signals

---

src/fw_fcp.c
src/hinawa_enum_types.h
tests/hinawa-enum

In AV/C Digital interface Command Set General Specification, any transactions are going
to be aborted at bus reset.
The series is the support for the behaviour, including code refactoring.
```
Takashi Sakamoto (6):
fw_fcp: code refactoring to check result of transaction
fw_fcp: code refactoring for lifetime of handler and lock
fw_fcp: maintain transaction in doubly-linked list
fw_fcp: iterate list entries for transactions
fw_fcp: use enumeration for state of transaction
fw_fcp: abort transaction at bus reset
src/fw_fcp.c            | 140 +++++++++++++++++++++++++++++++---------
src/hinawa_enum_types.h |   2 +
tests/hinawa-enum       |   1 +
3 files changed, 113 insertions(+), 30 deletions(-)
```

fw_fcp: abort transaction at bus reset

---

src/fw_fcp.c
src/fw_node.c
tests/fw-node

When multiple 1394 OHCI hardware are available, Linux FireWire subsystemmaintains them by numeric index. The instance of node device has a property about the numeric index and it is available in fw_cdev_get_info structure.
The numeric index is passed to an argument for Hinawa.FwResp::requested signal, thus it is convenient for user space application to retrieve the numeric index via property of Hinawa.FwNode.
The value of card_id is stable even if crossing bus reset, thus it is convenient for filtering request subaction.
This patchset introduces the property for numeric index.
```
Takashi Sakamoto (2):
fw_node: add card_id property for the numeric ID of 1394 OHCI hardware
fw_fcp: check card_id in requested event for transaction response
src/fw_fcp.c  |  6 +++---
src/fw_node.c | 22 …
```

[PATCH 0/2] fw_node/fw_fcp: support numeric index of 1394 OHCI hardware

---

README.rst
meson.build
src/meson.build
tests/meson.build

The recent version of meson build gained some useful features. This series follows to it.
```
Takashi Sakamoto (3):
meson: bump minimal dependency version up to 0.54.0 for
meson.override_dependency()
meson: bump minimal dependency version up to 0.56.0 for
meson.project_build_root()
meson: bump minimal dependency version up to 0.60.0 for list.<plus>
README.rst        | 4 ++--
meson.build       | 6 +++---
src/meson.build   | 8 ++------
tests/meson.build | 3 +++
4 files changed, 10 insertions(+), 11 deletions(-)
```

[PATCH 0/3] meson: declaration cleanup

---

.github/workflows/build.yml
README.rst
doc/hinawa.toml.in
doc/meson.build
doc/overview.md
src/cycle_time.c
src/fw_fcp.c
src/fw_fcp.h
src/fw_node.c
src/fw_req.c
src/fw_req.h
src/fw_resp.c
src/fw_resp.h
src/hinawa_enum_types.h
src/meson.build

This patch series update documentation as a preparation for version 4.0 release
```
Takashi Sakamoto (4):
doc: use the word '1394 OHCI hardware' for consistency
doc: obsolete usage of word 'unit' with 'node'
doc: update annotations for functions, properties, and signals
doc: annotate error domain available in gi-docgen 2023.1
.github/workflows/build.yml | 34 +++++++++++++++++++++++----
README.rst                  |  2 +-
doc/hinawa.toml.in          |  2 +-
doc/meson.build             |  2 +-
src/cycle_time.c            |  6 ++---
src/fw_fcp.c                | 47 +++++++++++++++++++------------------
src/fw_fcp.h                |  4 ++--
src/fw_node.c               | 26 ++++++++++----------
src/fw_req.c                | 42 ++++++++++++++++-----------------
src/fw_req.h                | 10 …
```

[PATCH 0/4] doc: improve documentation
